name: Deploy to AWS Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Code to AWS Server
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Connect to AWS Ubuntu Server and deploy
      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd quranappv2
            git pull origin main
            npm install
            pm2 restart all || pm2 start npm --name "quranappv2" -- run dev
