name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}

      # Ensure CSS files are in place
      - name: Copy CSS files
        run: |
          mkdir -p out/_next/static/css
          cp .next/static/css/*.css out/_next/static/css/

      # Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Deploy to Netlify
      - name: Deploy to Netlify
        run: netlify deploy --dir=out --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
